### ISSUE TITLE
About a  _ext file problem

### ISSUE THREAD

**Issue by AI-Hello** [uyzhang/PCT_Pytorch#18]
I want to_ Ext file, can you share it with me, email: 1621540694@qq.com

**Comment by uyzhang** [comment]
I compiled the files, you may not be able to use them, because the specific environment is different, you can try to compile `pip install pointnet2_ops_lib/.`

**Comment by AI-Hello** [comment]
在我安装的时候，提示我没有这个文件(pointnet2_ops_lib/.)

**Comment by uyzhang** [comment]
你可以将报错信息贴出来

**Comment by AI-Hello** [comment]
只提示了：ERROR: Invalid requirement: 'pointnet2_ops_lib/.'

**Comment by uyzhang** [comment]
你是如何操作的，我这边没有遇到过这个问题。

**Comment by AI-Hello** [comment]
你好，能否加个qq啥的。。。这样说不方便。一会删除此条评论可以吗

**Comment by uyzhang** [comment]
2570219563
