### ISSUE TITLE
Can you provide a pre-training model

### ISSUE THREAD

**Issue by aso538** [uyzhang/PCT_Pytorch#2]
hey bro！Can you provide a pre-training model? thanks！ My email is 277705821@qq.com

**Comment by uyzhang** [comment]
The path of the model is in ./checkpoints/train/models/model.t7

**Comment by uyzhang** [comment]
> hey bro！Can you provide a pre-training model? thanks！ My email is [277705821@qq.com](mailto:277705821@qq.com)

The path of the model is in ./checkpoints/train/models/model.t7

**Comment by uyzhang** [comment]
> hey bro！Can you provide a pre-training model? thanks！ My email is [277705821@qq.com](mailto:277705821@qq.com)

What is the pre-trained model?

**Comment by aragakiyuiii** [comment]
> > hey bro！Can you provide a pre-training model? thanks！ My email is [277705821@qq.com](mailto:277705821@qq.com)
> 
> What is the pre-trained model?

He means the trained PCT model's weight parameters, I guess.

**Comment by aragakiyuiii** [comment]
> > > hey bro！Can you provide a pre-training model? thanks！ My email is [277705821@qq.com](mailto:277705821@qq.com)
> > 
> > 
> > What is the pre-trained model?
> 
> He means the trained PCT model's weight parameters, I guess.

So he don't have to train the PCT model again if you can provide the trained model weight parameters.
