### ISSUE TITLE
unmet accuracy

### ISSUE THREAD

**Issue by yifita** [uyzhang/PCT_Pytorch#7]
Thanks for this implementation!

I ran the test code with
```
python main.py --exp_name=test --num_points=1024 --use_sgd=True --eval=True --model_path=checkpoints/best/models/model.t7 --test_batch_size=4
```
(changed test_batch_size to 4 from 8 due to GPU memory constraints)

But the accuracy is really bad:
```
Test :: test acc: 0.483387, test avg acc: 0.455517
```

The only thing i did slightly differently to the original code is that, I downloaded the h5 data manually instead of using the code, as otherwise i met certificate issues. 

Can anyone else replicate the 93% accuracy as reported in the repo?

**update**
setting --test_batch_size=1 achieves test acc: 0.932739, test avg acc: 0.899901
another observation, if test_batch_size > 1, prediction result is not reproducible / deterministic. 

I'm using pytorch 1.6.0

**Comment by uyzhang** [comment]
Thanks for your point,
I find some bugs when batch_size=1, but I can't replicate
